name: update Anykernel3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Anykernel3 branch 
        uses: actions/checkout@v4
        with: 
          ref: AnyKernel3
          fetch-depth: 0
      - name: Set up Git 
        run: | 
          git config --global user.name "GitHub Actions" 
          git config --global user.email "actions@github.com" 
      - name: Sync with Anykernel3 
        run: | 
          git remote add upstream https://github.com/osm0sis/AnyKernel3
          git branch -m master
          git pull upstream master --rebase
          git push origin master:AnyKernel3 --force